# Generated by Django 5.2 on 2025-05-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='availability',
            name='date',
            field=models.DateField(default='2025-05-05'),
            preserve_default=False,
        ),
    ]
