# Generated by Django 5.2 on 2025-05-04 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='canvas_ics_url',
            new_name='calendar_url',
        ),
    ]
