# Generated by Django 5.2 on 2025-05-04 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_canvas_ics_url_studentprofile_calendar_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='calendar_url',
        ),
    ]
