# Generated by Django 5.2 on 2025-05-05 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_studentprofile_calendar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='calendar_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
