# Generated by Django 5.2 on 2025-05-05 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_studentprofile_calendar_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='calendar_url',
            new_name='canvas_ics_url',
        ),
    ]
