from django.urls import path
from .views import (
    JobListCreateView,
    ApplyToJobView,
    StudentApplicationsView,
    ShiftListCreateView,
    AvailabilityListCreateView,
    StudentDashboardView,
    ManagerDashboardView,
    manager_dashboard_html,
    student_dashboard_html,
    jobs_available_view,
    post_job_view,
    manager_applications_view,
    manager_jobs_view,
    assign_shift_view,
    # submit_availability_view,
    manager_availability_view,
    delete_availability,
    edit_shift_view,
    delete_shift_view,
)

urlpatterns = [
    path('jobs/', JobListCreateView.as_view(), name='job-list-create'),
    path('apply/', ApplyToJobView.as_view(), name='apply-to-job'),
    path('my-applications/', StudentApplicationsView.as_view(), name='student-applications'),
    path('shifts/', ShiftListCreateView.as_view(), name='shifts'),
    path('availability/', AvailabilityListCreateView.as_view(), name='availability'),
    path('student-dashboard/', StudentDashboardView.as_view(), name='student-dashboard'),
    path('manager-dashboard/', ManagerDashboardView.as_view(), name='manager-dashboard'),
    path('dashboard/student/', student_dashboard_html, name='student-dashboard-html'),
    path('dashboard/manager/', manager_dashboard_html, name='manager-dashboard-html'),
    path('jobs/available/', jobs_available_view, name='jobs-available'),
    path('post-job/', post_job_view, name='post-job'),
    path('dashboard/manager/applications/', manager_applications_view, name='manager-applications'),
    path('dashboard/manager/my-jobs/', manager_jobs_view, name='my-jobs'),
    path('dashboard/manager/assign-shift/', assign_shift_view, name='assign-shift'),
    # path('availability/submit/', submit_availability_view, name='submit-availability'),
    path('availability/manage/', manager_availability_view, name='manager-view-availability'),
    path("availability/delete/<int:availability_id>/", delete_availability, name="delete-availability"),
    path('dashboard/manager/edit-shift/<int:shift_id>/', edit_shift_view, name='edit-shift'),
    path('dashboard/manager/delete-shift/<int:shift_id>/', delete_shift_view, name='delete-shift'),

]
